version: '3'
services:
  api:
    build:
      context: .
      dockerfile: api/docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - ./api/src:/myapp
      - gem_data:/usr/local/bundle
    ports:
      - "3001:3001"
    stdin_open: true
    tty: true
  app:
    build: ./app/docker
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./app/react:/myapp
  db:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

  cli:
    image: mysql:8.0.27
    networks:
      - mysql-network
    command: mysql -hdb -uuser -ppassword db

volumes:
  mysql-data:
  gem_data:

# ブリッジネットワーク を使って、アプリケーションコンテナとmysqlコンテナを通信可能に
networks:
  mysql-network:
    driver: bridge